### ISSUE TITLE
Three small improvements

### ISSUE THREAD

**Issue by kaklakariada** [exasol/project-keeper#470]
There are many small improvements we can make to the code:

* Upgrade Go version in workflow files to `"1.20"` (note the double quotes to avoid interpreting it as double number `1.2`)
* Replace deprecated Sonar property `sonar.login` with `sonar.token`
* Add step to free up ~14GB of space by deleting Android and Dotnet from GitHub runner:
    ```yml
      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
    ```
