### ISSUE TITLE
Remove step "Cache go-licenses" from project-keeper-verify.yml

### ISSUE THREAD

**Issue by kaklakariada** [exasol/project-keeper#479]
In workflow file `.github/workflows/project-keeper-verify.yml` action `actions/setup-go@v4` enables caching by default, so the separate step (`actions/cache@v3` with name `Cache go-licenses`) is not necessary any more.

Instead configure `actions/setup-go@v4` to also consider project keeper scripts that indirectly define the go-licenses version:

```yaml
  - uses: actions/setup-go@v4
    with:
      go-version: '1.20'
      cache-dependency-path: |
             go.sum
             .github/workflows/project-keeper-verify.yml
             .github/workflows/project-keeper.sh
```

Without this change, the cache action will generate errors when restoring the cache while files already exist.
