### ISSUE TITLE
Add goal javadoc:javadoc to ci-build-next-java.yml

### ISSUE THREAD

**Issue by ckunki** [exasol/project-keeper#486]
Add goal `javadoc:javadoc` to template for file `.github/workflows/ci-build-next-java.yml`:

```
- name: Run tests and build with Maven
  run: |
    mvn --batch-mode --update-snapshots clean javadoc:javadoc -DtrimStackTrace=false \
        -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
```

**Comment by kaklakariada** [comment]
This file already contains the following action:

```yaml
      - name: Run tests and build with Maven
        run: |
          mvn --batch-mode --update-snapshots clean package -DtrimStackTrace=false  \
              -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
```
The `package` Maven lifecycle already builds javadoc. In some projects the `javadoc` plugin is called explicitly, probably because `package` does not work there.
