### ISSUE TITLE
Allow specifying an environment for ci-build.yml

### ISSUE THREAD

**Issue by kaklakariada** [exasol/project-keeper#566]
Some projects need to specify an environment, e.g. https://github.com/exasol/exasol-test-setup-abstraction-java/

```yml
jobs:
  build:
    environment: aws
```

PK must allow specifying an optional environment for ci-build.yml
