### ISSUE TITLE
Allow excluding tests via JUnit tags

### ISSUE THREAD

**Issue by kaklakariada** [exasol/project-keeper#613]
PK generates `pk_generated_parent.pom` with empty property `test.excludeTags`:

```xml
    <properties>
        <test.excludeTags/>
    </properties>
```

This is unexpected in multi-module maven projects. Here it would be better to define this only in the top level pom file to avoid overriding the property in child modules.

## Task

Remove `test.excludeTags` property when the current maven module has a parent defined in `.project-keeper.yml` via

```yml
  - type: maven
    path: api/pom.xml
    parentPom:
      groupId: com.exasol
      artifactId: my-parent-module
      version: ${revision}
      relativePath: ../parent/pom.xml
```

## Workaround
Specify `test.excludeTags` in each individual maven module
