### ISSUE TITLE
Improve error handling for unknown jobs in workflow customization

### ISSUE THREAD

**Issue by kaklakariada** [exasol/project-keeper#614]
When specifying an unknown job ID like in the following `.project-keeper.yml`, PK fix fails with a unhelpful error message

```yml
        - action: REPLACE
          job: unknown-job-id
          stepId: sonar-analysis
          content:
            name: Sonar analysis
            id: sonar-analysis
```

Error message:

```
Cannot invoke "com.exasol.projectkeeper.validators.files.GitHubWorkflow$Job.insertStepAfter(String, com.exasol.projectkeeper.shared.config.workflow.WorkflowStep)" because "job" is null
```
