### ISSUE TITLE
Run ci build when a PR is marked as ready for review

### ISSUE THREAD

**Issue by YotillaAntoni** [exasol/project-keeper#620]
Currently the generated `ci-build.yml` includes this snippet to run the workflow when there are changes to the PR:

```
on:
  ...
 
  pull_request: null
```

According to [docs](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request) this includes the activity types: `opened`, `synchronize` and  `reopened`

There is a fourth activity type `ready_for_review` that would be helpful to also include, so the build is triggered when a PR is converted from Draft to Ready for review.

This is useful because the build might be customized to avoid expensive tests when the PR is still a draft.

To support this PK should generate:

```
on:
  ...
 
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
```
