### ISSUE TITLE
Pin the `security-issues` action in the `dependencies_check.yml` template

### ISSUE THREAD

**Issue by ArBridgeman** [exasol/project-keeper#641]
# Summary
In the PTB, we want to automate updating the PTB version in `exasol/python-toolbox/.github/actions/security-issues` . This automation will occur during the release process, which means that there will be an time gap between when a release is prepared & a new version is actually released. The `project-keeper`  `dependencies_check.yml` template needs to be updated to be pinned to a specific version (not main) of the action to avoid breaking changes during such a delay. After updating the template, a new `project-keeper` version should be released & propagated to affected repos.

```yaml
# before
      - name: Report Security Issues
        id: security-issues
        uses: exasol/python-toolbox/.github/actions/security-issues@main
# after
      - name: Report Security Issues
        id: security-issues
        uses: exasol/python-toolbox/.github/actions/security-issues@1.0.0
```

If desired, this could be coupled with https://github.com/exasol/project-keeper/issues/638.
