### ISSUE TITLE
Update webhook url for creating new pull request with dependency updates

### ISSUE THREAD

**Issue by skyglass** [exasol/project-keeper#657]
The mechanism for generating the PRs is in project keeper. Please change the following things as decided in the retro:
* Set the schedule for the dependency check and update from daily to weekly. 
* Sunday night  would be ideal, since we can then act on Monday.
* Change the webhook secret that is used to this channel

Excerpt from PK-generated workflow (here from https://github.com/exasol/exasol-virtual-schema/blob/1c0ec6b4f7d510ad0dd973c4e575fa6d0704d06f/.github/workflows/dependencies_check.yml#L54C2-L62C21)

```
 start_dependency_udpate:
    needs: report_security_issues
    # [impl->dsn~trigger-dependency-updates~1]
    if: ${{ needs.report_security_issues.outputs.created-issues }}
    concurrency:
      cancel-in-progress: true
      group: "dependencies_update"
    # Workflow needs secret INTEGRATION_TEAM_SLACK_NOTIFICATION_WEBHOOK
    secrets: inherit
```

The Slack app is created. The webhook is in secret INTEGRATION_TEAM_SECURITY_UPDATES_WEBHOOK .
